language: python
python:
- "2.7"
env:
- TOXENV=py27
matrix:
  include:
    - python: "2.7"
      env: TOXENV=lint
    - python: "2.7"
      env: TOXENV=py27
    - python: "pypy"
      env: TOXENV=pypy
    - python: "2.7"
      env: TOXENV=jy27
  allow_failures:
    - python: "pypy"
      env: TOXENV=pypy
    - python: "2.7"
      env: TOXENV=jy27
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils xsltproc
install:
  - pip install -U setuptools pip wheel jip
  - pip install -U zc.buildout tox
  - buildout
  - tox --version
  - sort --version
  - env | sort
  - if [ "$TOXENV" == "jy27" ]; then make install-jython; fi
script:
  - tox
